language: node_js
node_js:
  - node
addons:
 sauce_connect: true
 jwt:
   secure: FGd3nLc8dZNsJVBKl3HAs5StmzOm4Rmok5odgUxfUfxcqSoB7vivpDLzSaDf/6lgaTnasRNrK07L0ImLqhWXOZFwIBBJ7GEiTiK0pLF9vaDnxoCj7zYymahoL8f6cQKU1n0wHwHnj0m584ySZ9kfCTfmYAHoUvbTkbZAT185QbzsWoinxsA19ZPLfmbnuZhaSCNho8TCt2qNkfauS6OmK1VU6JAtKgN9M0vBmXGoBl0DsvmFON8ybgx/CJ/0bbhNvdhAhsdRMvsm2g7iNGV71VDBrb+ceD+el1/ELsj2XmhSFM7gJPVteC611YWmqRl7okLCbHejnRVvKYRoVcpUyYd2U/ZdTux8CiQ4mWXtYN/crRtx4JAyYQFAeflBW0ZoeerEWjWiuU/XpFloQrOeVQhC3Xf5YWjy3/LPePbNrVGVLgN331+wo17dvE9S+q4fSIPp+Mmq1T+sxLwllIEZr1dz7mX0hAciDV0o8T1TxkJdhaXzLwLDgDCrmJ+htekpW6fayRfHXTbS3D75sC7DGPgA9EksxoB5BlJDBg3gcsvHxEX/X7vjShTlpFZ57c6owXsekPkHHQRWavoeYsHfmD9Vm525jcDHNVf8stCA5a5uBVb9Yw8IjRmxdmG7pDZoJ/AKxdCPagfpSVfrxT8PPF54PXO274nYl/mIcd5u4Hk=

before_script:
 - npm start & WEBPACK_SERVER_PID=$!
 - sleep 10 # give webpack some time to start

script:
 - npm run test:ci
 - npm run e2e:ci

after_script:
 - kill WEBPACK_SERVER_PID

before_deploy:
  - npm run build:example
  - sed -i 's/href="\/"/href="\/ng-lazyload-image\/"/g' ${TRAVIS_BUILD_DIR}/example-dist/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: example-dist
  target_branch: gh-pages
  on:
    branch: master
